package A3_View;

import A2_Model.Pegawai;
import A2_Model.Controller;
import A2_Model.Manager;
import A2_Model.Payroll;
import A2_Model.Sales;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;

public class Penggajian extends javax.swing.JFrame {
    private Controller controller;
    private Payroll pes;
    
    public Penggajian(Payroll payroll) {
        controller = new Controller(payroll);
        initComponents();
        
    }

    public Controller getController (){
        return controller;
    }

    public Penggajian() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPegawai = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnManager = new javax.swing.JButton();
        btnDataBase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        cboBulan = new javax.swing.JComboBox<>();
        cboTahun = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        btnCetak = new javax.swing.JButton();
        btnClearSlip = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Payrol Radar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setText("PERIODE : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 153));
        jLabel8.setText("PENGGAJIAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 51, 0));
        jLabel7.setText("SLIP GAJI");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("DATA BASE PEGAWAI");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 270, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("KEPEGAWAIAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 190, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SISTEM INFORMASI MANAGEMENT YAYASAN RADAR ALAM DAMAI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 950, -1));

        btnPegawai.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A1_Gambar/p1. reg pegawai.png"))); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        btnSales.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A1_Gambar/P2. reg sales.png"))); // NOI18N
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, -1));

        btnManager.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A1_Gambar/P3. reg manager.png"))); // NOI18N
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });
        getContentPane().add(btnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 140, -1));

        btnDataBase.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnDataBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A1_Gambar/p4. database.png"))); // NOI18N
        btnDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 140, -1));

        screen.setColumns(20);
        screen.setRows(5);
        jScrollPane1.setViewportView(screen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 510, 270));

        cboBulan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Bulan -", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(cboBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 123, -1));

        cboTahun.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Tahun -", "2021", "2022", "2023", "2024", "2025" }));
        getContentPane().add(cboTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, -1, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 51, 51));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setText("PERIODE : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, -1, -1));

        display.setColumns(20);
        display.setRows(5);
        jScrollPane2.setViewportView(display);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 660, 270));

        btnCetak.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A1_Gambar/p5. cetak gaji.png"))); // NOI18N
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 140, -1));

        btnClearSlip.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnClearSlip.setForeground(new java.awt.Color(255, 0, 0));
        btnClearSlip.setText("RESET");
        btnClearSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSlipActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearSlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A1_Gambar/background.png"))); // NOI18N
        jLabel4.setText("a");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        inputPegawai dialog = new inputPegawai(this,true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        inputSales dialog = new inputSales(this,true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        inputManager dialog = new inputManager(this,true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBaseActionPerformed
        display.append("JABATAN \t\t| NAMA  \t\t| GAJI POKOK \t| TUNJANGAN/BONUS " +
                       "\n------------------------------------------------" +
                       "--------------------------------------------------" +
                       "---------------------------------------------------\n");
        
        for (Pegawai p : controller.getPayrollOn().getListPegawai()){
            display.append(p.cetakData());
            }
        display.append("\n");
        
    }//GEN-LAST:event_btnDataBaseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        display.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        Payroll pay = new Payroll((String) cboBulan.getSelectedItem(), 
                                  (String) cboTahun.getSelectedItem());
      
        pes = pay;
      
        for (Pegawai p : controller.getPayrollOn().getListPegawai()){
            screen.append(pes.CetakDeskripsi());
            screen.append(p.cetakGaji());
            }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnClearSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSlipActionPerformed
        screen.setText("");
    }//GEN-LAST:event_btnClearSlipActionPerformed

    public static void main(String args[]) {    
        Payroll payroll = new Payroll("", "");
        payroll.registrasiPegawai(new Pegawai("Pegawai Tetap", "Wahyu Wiradarma", 1935000));
        payroll.registrasiPegawai(new Manager("Manager", "Fahmy Alamsyah", 2350000,250000));
        payroll.registrasiPegawai(new Sales("Sales", "Ammar Setiawan", 1935000,125000));
        payroll.registrasiPegawai(new Pegawai("Pegawai Tetap", "Ilfan Elliyin Mabrur", 1935000));
       



        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penggajian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Penggajian p = new Penggajian(payroll);
                p.setExtendedState(JFrame.MAXIMIZED_BOTH);
                p.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearSlip;
    private javax.swing.JButton btnDataBase;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnSales;
    private javax.swing.JComboBox<String> cboBulan;
    private javax.swing.JComboBox<String> cboTahun;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea screen;
    // End of variables declaration//GEN-END:variables
}
